site_name: My Docs
site_url: https://eshaben.github.io/test-docs/
docs_dir: docs
copyright: © 2024 Moonbeam Foundation. All Rights Reserved.
theme:
  name: material
  custom_dir: material-overrides
  favicon: /assets/images/Moonbeam-Favicon-50.webp
  logo: /assets/images/moonbeam-logo.webp
  font:
    text: Open Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search
  - awesome-pages
  # - git-revision-date-localized:
  #     exclude:
  #       - .snippets/*
  #     enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
  #     enable_creation_date: !!bool true
extra:
  version:
    provider: mike
